version: '3.7'

networks:
  default:
    name: course-network

volumes:
  database:

services:
  mongo:
    image: mongo:4.4.4-bionic
    container_name: "course-mongo"
    hostname: course-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - database:/data/db
